version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.31
    container_name: mssc-mysql
    ports:
      - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=vLDIdlOo2mHpnW=u4vkuT`LDN"
    volumes:
      - /data/data1/var/db/mssc:/var/lib/mysql
  jms:
    image: vromero/activemq-artemis
    ports:
      - '8161:8161'
      - '61616:61616'
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
  eureka:
    image: gadb2/mssc-brewery-eureka
    ports:
      - '8761:8761'
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
  config:
    image: gadb2/mssc-config-server
    ports:
      - '8888:8888'
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_CLOUD_DISCOVERY_ENABLED: true
  inventory-failover:
    image: gadb2/mssc-beer-inventory-failover-service
    ports:
      - '8084:8084'
    depends_on:
      - eureka
      - config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_CLOUD_DISCOVERY_ENABLED: true
  inventory:
    image: gadb2/mssc-beer-inventory-service
    ports:
      - '8082:8082'
      - '8998:8998'
    depends_on:
      - eureka
      - config
      - mysqldb
      - jms
      - inventory-failover
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_DISCOVERY_ENABLED: true
  beer:
    image: gadb2/mssc-beer-service
    ports:
      - '8080:8080'
      - '8999:8999'
    depends_on:
      - eureka
      - config
      - mysqldb
      - jms
      - inventory
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_DISCOVERY_ENABLED: true
      SFG_BREWERY_BEERINVENTORYSERVICEHOST: http://inventory:8082
  order:
    image: gadb2/mssc-beer-order-service
    ports:
      - '8081:8081'
    depends_on:
      - eureka
      - config
      - mysqldb
      - jms
      - inventory
      - beer
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_DISCOVERY_ENABLED: true
      SFG_BREWERY_BEERSERVICEHOST: http://beer:8080

#  testbed:
#    image: ubuntu:trusty
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
